### ISSUE TITLE
Using hazelcast 3.11 causes java.lang.NoSuchMethodError in HzMap.getValueOrNull

### ISSUE THREAD

**Issue by robreinert** [hazelcast/hazelcast-scala#23]
I get the following exception when using hazelcast-all-3.11 with hazelcast-scala 3.9.1

It looks like 3.11 added an extra Address callerAddress parameter.

com.hazelcast.client.UndefinedErrorCodeException: Class name: java.lang.NoSuchMethodError, Message: com.hazelcast.map.impl.recordstore.RecordStore.get(Lcom/hazelcast/ni
o/serialization/Data;Z)Ljava/lang/Object;
        at com.hazelcast.Scala.HzMap.getValueOrNull(HzMap.scala:63)
        at com.hazelcast.Scala.HzMap.$anonfun$getFastIfLocal$3(HzMap.scala:46)
        at scala.collection.Iterator$$anon$10.next(Iterator.scala:457)
        at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:510)
        at scala.collection.Iterator.foreach(Iterator.scala:944)
        at scala.collection.Iterator.foreach$(Iterator.scala:944)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1432)
        at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:59)
        at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:50)
        at scala.collection.parallel.immutable.LazyParVectorCombiner.$plus$plus$eq(ParVector.scala:95)
        at scala.collection.parallel.AugmentedIterableIterator.flatmap2combiner(RemainsIterator.scala:131)
        at scala.collection.parallel.AugmentedIterableIterator.flatmap2combiner$(RemainsIterator.scala:126)
        at scala.collection.parallel.immutable.ParHashMap$ParHashMapIterator.flatmap2combiner(ParHashMap.scala:76)
        at scala.collection.parallel.ParIterableLike$FlatMap.leaf(ParIterableLike.scala:1070)
        at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:49)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:63)
        at scala.collection.parallel.Task.tryLeaf(Tasks.scala:52)
        at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:46)
        at scala.collection.parallel.ParIterableLike$FlatMap.tryLeaf(ParIterableLike.scala:1066)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal(Tasks.scala:156)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal$(Tasks.scala:153)
        at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:436)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:146)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:145)
        at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:436)
        at java.util.concurrent.RecursiveAction.exec(Unknown Source)
        at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.util.concurrent.ForkJoinTask.doJoin(Unknown Source)
        at java.util.concurrent.ForkJoinTask.join(Unknown Source)
        at scala.collection.parallel.ForkJoinTasks$WrappedTask.sync(Tasks.scala:375)
        at scala.collection.parallel.ForkJoinTasks$WrappedTask.sync$(Tasks.scala:375)
        at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.sync(Tasks.scala:436)
        at scala.collection.parallel.ForkJoinTasks.executeAndWaitResult(Tasks.scala:419)
        at scala.collection.parallel.ForkJoinTasks.executeAndWaitResult$(Tasks.scala:412)
        at scala.collection.parallel.ForkJoinTaskSupport.executeAndWaitResult(TaskSupport.scala:56)
        at scala.collection.parallel.ExecutionContextTasks.executeAndWaitResult(Tasks.scala:551)
        at scala.collection.parallel.ExecutionContextTasks.executeAndWaitResult$(Tasks.scala:551)
        at scala.collection.parallel.ExecutionContextTaskSupport.executeAndWaitResult(TaskSupport.scala:80)
        at scala.collection.parallel.ParIterableLike$ResultMapping.leaf(ParIterableLike.scala:956)
        at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:49)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:63)
        at scala.collection.parallel.Task.tryLeaf(Tasks.scala:52)
        at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:46)
        at scala.collection.parallel.ParIterableLike$ResultMapping.tryLeaf(ParIterableLike.scala:951)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:149)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:145)
        at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:436)
        at java.util.concurrent.RecursiveAction.exec(Unknown Source)
        at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
        at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
        at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
        at ------ submitted from ------.(Unknown Source)
        at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:127)
        at com.hazelcast.spi.impl.AbstractInvocationFuture$1.run(AbstractInvocationFuture.java:250)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
        at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
        at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)

**Comment by nilskp** [comment]
Fixed in fd82ad120107b3c9e8f0dfd8d134dbdc689b5508.

[3.11.0](https://bintray.com/hazelcast/maven/hazelcast-scala/3.11.0) has been released.

**Comment by robreinert** [comment]
(thumbsup)
